---
title: |
 | Using JDemetra+ in R: from version 2 to version 3 
 | Presentation 3: Wrangling workspaces in R
subtitle: "TSACE Webinar, Wednesday December 14th 2022"
author: "Anna Smyk and Tanguy Barthelemy"
division: |
    | With the collaboration of Alain Quartier-la-tente
    | 
logo: "img/SACElogo"
automaticcontents: true
automaticcontentstext: "Contents"
output:
    beamer_presentation:
        template: template_Beamer.tex
        keep_tex: yes
        theme: TorinoTh
        slide_level: 3
        includes:
          in_header: preamble_beamer.tex
themeoptions: "coding=utf8,language=english"
classoption: 'usepdftitle=false,french' #handout
fontsize: 10pt
bibliography: [biblio.bib]
biblio-style: unsrtnat
natbiboptions: [numbers]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      eval = FALSE, 
                      cache = F, 
                      fig.align = 'center',
                      fig.path = "img/markdown-")
library(knitr)
library(kableExtra)
library(microbenchmark)
library(ggplot2)
library(rjd3toolkit)
library(rjd3modelling)
library(rjd3sa)
library(rjd3arima)
library(rjd3x13)
library(rjd3tramoseats)
library(rjdemetra3)
library(ggdemetra3)

# library(rjd3sts)
# library(rjd3highfreq)

# library(rjd3bench)
fig.ext <- "pdf"
is_html <- knitr::is_html_output()
is_latex <- knitr::is_latex_output()
fig.ext = "pdf"
if (is_html) {
    fa_arrow_circle_right <- '<i class="fas fa-arrow-circle-right"></i>'
    fa_r_project <- '<i class="fab fa-r-project"></i>'
} else {
    if (is_latex) {
        fa_arrow_circle_right <- "\\faIcon{arrow-circle-right}"
        fa_r_project <- "\\faIcon{r-project}"
        fa_java <- "\\faIcon{java}"
    }else {
        fa_arrow_circle_right <- "->"
        fa_r_project <- 'R'
    }
}
options(width = 60)
def.par <- par(no.readonly = TRUE)
```



# Introduction

Mise en page : 
package en gras, code en quote

### Context 

- a workspace is a JD+ specific data structure (xml files) which allows to use the GUI and cruncher 

- in R we don't need this stucture to run an SA process (cf P2)

- we could think sa processing with JD+ algorithms can happen in two disntict worlds 
  - GUI and cruncher using workspaces OR
  - R functions (without workpaces, TS object or numeric vectors for HF)

Still there are benefits in using workspaces and R packages in conjunction

We will highlight them in the remaining of this presentation 



# Using workspaces and R packages in conjuction

### Using workspaces and R packages in conjuction 

Two (?) classes of benefits

- instant reading: immersing results in the R world (functions, plots..)

- automating potential manual operations 

De manière générale, aucune compatibilité entre v2 et v3



# Instant reading

v2 : `RJDemetra::load_workspace()` --> creation of RJD object (java object pointer)
v3 : `rjdemetra3::load_workspace()` --> readable R object (list format)

avantage : to directement dans l'environnement R
--> mettre bout de code lecture de série get_boject
--> doc de traavil


# Automating operations

### Automating operations on workspaces 

Goal: to produce and to reproduce the workspace structure without the JDemetra+ graphical interface but with R and keeping the read, write and refresh properties both by the graphical interface and by the cruncher.

Cruncher and GUI react the same way to a WS :

- if the structure is not good : they won't be able to read anything
- if the structure is minimal : they will manage to only read and compute the SA-items
- if the ws are well-structured and have all the necessairy information : they will succeed to read, compute and refresh with the chosen policy our sa-items.

### Outline of the automation

Presentation in v2

operations :

- creation 
- export / write 
- modifications / dynamic update

### Creation

- `RJDemetra::new_workspace()` : creation of workspace
- `RJDemetra::new_multiprocessing()` : creation of multiprocessing
- to create a spec, there is several functions :
`RJDemetra::x13_spec(), RJDemetra::tramoseats_spec(), ...` and also in v3 with packages `rjd3tramoseats` and `rjd3x13`
- to create an SA-item, there is several functions depending on the chosen spec :
`RJDemetra::x13(), RJDemetra::tramoseats(), ...` and also in v3 with packages `rjd3tramoseats` and `rjd3x13`
- Finally you can use `RJDemetra::add_sa_item()` to add the created SA-item to a multprocessing in your workspace

### Export

The function `RJDemetra::save_workspace()` export and create a physical workspace with a structure in folder and xml files. But it only creates what the previous functions constructed. 

For example, the production line `RJDemetra::x13(...) |> RJDemetra::add_sa_item(...) |> RJDemetra::save_workspace(...)` create an XML file without any metadata --> no link with the raw data !

### Summary

RJD2 --> virtual WS --> physical XML (minimal)
rjdWS : modify uniquement physical WS
GUI & Cruncher --> read at least minimal XML and refresh with a completed XMl

### rjdworkspace and dynamic update

Ici on discute le package rjdws développer par l'Insee.
rjdws est un package qui ... Ce package s'appuie sur RJDv2
Les packages v3 ne sont pas encore développés pour la gestion de WS.

### Automating one WS

("functions that operate on one workpace")
- series object
- spec 
- meta data
in v2 RJDemetra 
in v3 rjdworkpace and other rjd3...

### Automating with several WS

### Merging workspaces 
("functions that operate two workpaces")
context: annual rev

in v2 RJDemetra 
in v3 rjdworkpace and other rjd3...

### Preserving desirable properties ?

two features to preserve
- GUI readable 
- Crunchable 

When are the preserved and when not ?


# Conclusion

### Summary of functionnalities 

- available 

- missing 



### Package's perimeter and  ressources

- V2 vs V3: not clear cut yet
not many features are available in sheer v3
rjdworkspace (predating v3) functions will be (partly) integrated into rjdemetra3 package





